[build]
  command = "npm run build"
  publish = "dist"

# Ensure SPA routing works (all routes serve index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
